### ISSUE TITLE
functional state manage

### ISSUE THREAD

**Issue by Sylvenas** [karranb/functional-spaceship-game#14]
``` js
const modelFunctions = (model, state) => ({

  getState: () => state,

  assignState: newProps => model({ ...state, ...newProps }),

  getProp: name => getProp(state, name),

})
```
assignState will return a new instance , how can I keep the instance , because I might use it elsewhere.

for example: 
``` js
const defaultState = {
    lines: [],
}
const Line = state => ({
    ...modelFunctions(Line)({
        ...defaultState,
        ...state
    })
})

const initLines = Line({lines:[{id:'line1'}]})
```

Assume there are two buttons named `addLine` and `getLines`
``` js
addLine.onClick=function(){
      lines.assignState({lines:[{id:'line1'},{id:'line2'}]})  // will return a new instance
}

getLines.onClick=function(lines){
      lines.getProp('lines') // get the lines
}
```

How does the `getLines` button get the added lines, because `addLine` will return a new instance  instead modify the `initLines`.

Thanks a lot.

**Comment by karranb** [comment]
Javascript is not fully functional which forces us to mutate data sometimes. 
I'm thinking of two approaches can solve your problem:

1. propagate the new instance
```
const updateListeners = instance => {
  addLine.onClick = function() {
    const newInstance = instance.assignState({ lines: [{ id: 'line1}, {id: 'line2'}]})
    updateListeners(newInstance)
  }
  getLines.onClick = function(instance) {
    instance.getProp('lines')
  }
}
```

2. create a mutable variable that saves the state
```
let lines
addLine.onClick = function() {
  lines.assignState({lines:[{id:'line1'},{id:'line2'}]})  // will return a new instance
}
getLines.onClick = function() {
  lines.getProp('lines')
}
```

Makes sense? I can try to elaborate about it a little more if you feel the need 😄

**Comment by Sylvenas** [comment]
Thanks bro，I understand the two solutions above.

1.propagate the new instance --closure
2.create a mutable variable that saves the state -- mutable variable/shared state

[State machine](https://en.wikipedia.org/wiki/Finite-state_machine) can solve this problem better？

**Comment by karranb** [comment]
yes, you are right, I think state machine is the best way to solve this if the `addline` `onclick` always assign the same state to lines. If you don't want to implement a state machine by yourself, [XState](https://xstate.js.org/docs/) is a good alternative.
